In [1]:
import torch
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import lightning.pytorch as pl
from lightning.pytorch.callbacks import RichProgressBar, Timer

# Add the prime_torch file to the system path so we can import it
import sys
sys.path.append("/glade/u/home/cobrien/prime/prime_lib/primesw")
from data import SWDataset, SWDataModule
from prime_torch import crps, SWRegressor

DATAPATH = '~/data/'

In [2]:
target_features = [
    'mms1_dis_bulkv_gse_fast_0', # V GSE X
    'mms1_dis_bulkv_gse_fast_1', # V GSE Y
    'mms1_dis_bulkv_gse_fast_2', # V GSE Z
    # 'mms1_dis_numberdensity_fast', # Ni
    # 'mms1_dis_temppara_fast', # Ti parallel to B
    # 'mms1_dis_tempperp_fast', # Ti perpendicular to B
    'mms1_des_numberdensity_fast', # Ne
    'mms1_fgm_b_gse_srvy_l2_0', # B GSE X
    'mms1_fgm_b_gse_srvy_l2_1', # B GSE Y
    'mms1_fgm_b_gse_srvy_l2_2', # B GSE Z
]
input_features = [
    'Np', # Ni
    'V_GSE_0', # V GSE X
    'V_GSE_1', # V GSE Y
    'V_GSE_2', # V GSE Z
    'THERMAL_SPD', # Vth
    'BGSE_0', # B GSE X
    'BGSE_1', # B GSE Y
    'BGSE_2', # B GSE Z
    'PGSE_0', # Wind Position GSE X
    'PGSE_1', # Wind Position GSE Y
    'PGSE_2', # Wind Position GSE Z
]
position_features = [
    # 'mms1_mec_r_gse_0', # MMS Position GSE X
    # 'mms1_mec_r_gse_1', # MMS Position GSE Y
    # 'mms1_mec_r_gse_2', # MMS Position GSE Z
    'r_gse_x', # MMS Position GSE X FROM LABEL FILE
    'r_gse_y', # MMS Position GSE Y FROM LABEL FILE
    'r_gse_z', # MMS Position GSE Z FROM LABEL FILE
]

trn_bounds = ['20151007 12:08:00+0000', '20211217 04:33:00+0000']
tst_bounds = ['20211217 04:34:00+0000', '20221206 11:21:00+0000']
val_bounds = ['20221206 11:22:00+0000', '20230601 14:21:00+0000']
datamodule = SWDataModule(
    target_features = target_features,
    input_features = input_features,
    position_features = position_features,
    region = 'solar wind',
    cadence = '100s',
    interpolate = True,
    window = 100,
    stride = 10,
    interp_frac = 0.1,
    trn_bounds = trn_bounds,
    val_bounds = val_bounds,
    tst_bounds = tst_bounds,
    datastore = "~/data/combined_data.h5",
    in_key = "wind_1min_complete",
    tar_key = "mms_1min_labeled",
)
datamodule.setup()

2025-10-03 10:31:56.468 | INFO     | data:__init__:97 - Segmenting input data.
2025-10-03 10:32:43.825 | INFO     | data:setup:274 - Train dataloader is ready. Dataset size: 165972
2025-10-03 10:32:45.274 | INFO     | data:__init__:97 - Segmenting input data.
2025-10-03 10:33:00.245 | INFO     | data:setup:295 - Validation dataloader is ready. Dataset size: 55354
2025-10-03 10:33:01.783 | INFO     | data:__init__:97 - Segmenting input data.
2025-10-03 10:33:16.903 | INFO     | data:setup:316 - Test dataloader is ready. Dataset size: 54629

In [3]:
model = SWRegressor(
    in_dim = len(input_features),
    tar_dim = len(target_features),
    pos_dim = len(position_features),
    decoder_type = 'linear',
    encoder_type = 'rnn',
    lr_scheduler = 'cosine',
    decoder_hidden_layers = [4],
    encoder_hidden_dim = 4,
    pos_encoding_size=4,
    encoder_num_layers=2,
    loss='mae',
)

In [4]:
logger = pl.loggers.TensorBoardLogger(
    save_dir = "~/data/prime/tensorboard_logs",
    name = 'test_model',
)

In [5]:
trainer = pl.Trainer(
    accelerator='cpu',
    max_epochs=1,
    callbacks = [
        Timer(), 
        RichProgressBar(),
        # ModelCheckpoint(),
        ],
    logger = logger,
    # precision='16-true', #Lower the precision to not blow up memory
)

💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
GPU available: True (cuda), used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
/glade/work/cobrien/conda-envs/pt212gpu_conda/lib/python3.11/site-packages/lightning/pytorch/trainer/setup.py:177: GPU available but not used. You can set it by doing `Trainer(accelerator='gpu')`.

In [ ]:
trainer.fit(model=model, datamodule=datamodule)

2025-09-30 13:32:32.397 | INFO     | data:__init__:97 - Segmenting input data.

In [2]:
import omegaconf
config = "/glade/u/home/cobrien/prime/prime_lib/configs/testing_config.yaml"

cfg = omegaconf.OmegaConf.load(
    config
)

trn_bounds = ['20151007 12:08:00+0000', '20151101 00:00:00+0000']
tst_bounds = ['20151101 00:01:00+0000', '20151201 00:00:00+0000']
val_bounds = ['20151201 00:01:00+0000', '20160101 00:00:00+0000']
datamodule = SWDataModule(
    target_features = cfg.data.target_features,
    input_features = cfg.data.input_features,
    position_features = cfg.data.position_features,
    region = cfg.data.region,
    cadence = cfg.data.cadence,
    interpolate = cfg.data.interpolate,
    window = cfg.data.window,
    stride = cfg.data.stride,
    interp_frac = cfg.data.interp_frac,
    trn_bounds = trn_bounds,
    val_bounds = val_bounds,
    tst_bounds = tst_bounds,
    batch_size = cfg.opt.batch_size,
    num_workers = cfg.opt.num_workers,
    datastore = cfg.data.datastore,
    in_key = cfg.data.in_key,
    tar_key = cfg.data.tar_key,
)
datamodule.setup()

2025-10-06 14:00:50.233 | INFO     | data:__init__:97 - Segmenting input data.
2025-10-06 14:00:52.141 | INFO     | data:setup:275 - Train dataloader is ready. Dataset size: 219
2025-10-06 14:00:53.926 | INFO     | data:__init__:97 - Segmenting input data.
2025-10-06 14:01:03.028 | INFO     | data:setup:296 - Validation dataloader is ready. Dataset size: 839
2025-10-06 14:01:04.823 | INFO     | data:__init__:97 - Segmenting input data.
2025-10-06 14:01:15.649 | INFO     | data:setup:317 - Test dataloader is ready. Dataset size: 938

In [3]:
datamodule.trn_ds.input_data.shape

torch.Size([219, 200, 11])

In [4]:
in_df = datamodule.raw_in_data
tar_df = datamodule.target_data
# in_df.index = in_df['Epoch']
# tar_df.index = tar_df['Epoch']

In [47]:
in_df.loc[in_df['Epoch'].isin(pd.to_datetime(datamodule.trn_ds.target_timestamps, utc = True)), :]

,Epoch,Np,V_GSE_0,V_GSE_1,V_GSE_2,V_GSM_0,V_GSM_1,V_GSM_2,THERMAL_SPD,Pressure,...,BGSE_1,BGSE_2,PGSM_0,PGSM_1,PGSM_2,PGSE_0,PGSE_1,PGSE_2,interped_mfi,interped_swe
52568,2015-10-07 12:08:00+00:00,37.848801,-421.844780,-57.495757,2.649977,-421.844780,-47.503039,32.499990,38.694366,11.475130,...,11.480245,-2.484772,260.039261,-11.117051,26.815990,260.039261,-23.560639,16.958258,False,False
52569,2015-10-07 12:09:00+00:00,36.212199,-421.786779,-58.262431,4.867046,-421.786779,-46.989176,34.788163,37.877690,10.982517,...,11.216154,-3.288038,260.039047,-11.126618,26.814068,260.039047,-23.562934,16.958303,False,False
52570,2015-10-07 12:10:00+00:00,34.793735,-421.191266,-58.709811,7.121441,-421.191266,-46.189193,36.934623,37.088497,10.528293,...,11.375124,-4.923737,260.038849,-11.136267,26.812108,260.038849,-23.565229,16.958349,False,False
52571,2015-10-07 12:11:00+00:00,34.356223,-418.904190,-57.961604,9.459100,-418.904190,-44.345610,38.503862,36.592814,10.282809,...,11.246658,-5.409140,260.038651,-11.145996,26.810111,260.038651,-23.567525,16.958394,False,False
52572,2015-10-07 12:12:00+00:00,34.988525,-413.384531,-67.945614,9.340852,-413.384531,-52.927828,43.615814,35.944780,10.282210,...,11.247777,-3.654909,260.038437,-11.155809,26.808077,260.038437,-23.569820,16.958439,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78678,2015-10-25 15:18:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True
78679,2015-10-25 15:19:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True
86676,2015-10-31 04:36:00+00:00,6.821851,-335.203345,-14.291337,6.646040,-335.203345,-11.346793,10.939032,33.509903,1.284921,...,5.304275,1.464514,237.139626,-78.182762,41.375338,237.139626,-87.386654,13.712755,False,False
86677,2015-10-31 04:37:00+00:00,6.913025,-335.988136,-12.726503,2.914493,-335.988136,-11.082896,6.901273,31.602618,1.307433,...,5.407705,1.512655,237.138817,-78.151089,41.437737,237.138817,-87.387924,13.712531,False,False
86679,2015-10-31 04:39:00+00:00,6.855100,-335.895493,-14.374802,2.918283,-335.895493,-12.623518,7.468561,30.266557,1.296145,...,5.407440,1.595073,237.137215,-78.087601,41.562458,237.137215,-87.390457,13.712084,False,False

In [48]:
tar_df.loc[
            (tar_df['Epoch'] <= trn_bounds[1])&
            (tar_df['Epoch'] >= trn_bounds[0]), :
        ]

,Epoch,probe,ratio_max_width,ratio_high_low,norm_Btot,small_energy_mean,large_energy_mean,temp_total,r_gse_x,r_gse_y,...,mms1_fgm_flag_srvy_l2,count_fgm,mms1_mec_r_gsm_0,mms1_mec_r_gsm_1,mms1_mec_r_gsm_2,mms1_mec_r_gse_0,mms1_mec_r_gse_1,mms1_mec_r_gse_2,count_mec,stable
27837,2015-10-07 12:08:00+00:00,mms1,0.162937,1.028892,0.327944,4.367644,4.493833,43.976894,50239.470379,57225.698595,...,0.0,960,50230.090765,46898.637686,-32985.835796,50230.090765,57236.914600,-3388.686355,2,1.0
27838,2015-10-07 12:09:00+00:00,mms1,0.187164,1.028944,0.326636,3.565465,3.668665,36.843220,50201.871120,57270.470353,...,0.0,960,50192.437640,46942.559927,-33001.676031,50192.437640,57281.624841,-3395.587946,2,1.0
27839,2015-10-07 12:10:00+00:00,mms1,0.193555,0.914468,0.314192,3.661464,3.348291,37.095240,50164.083466,57315.026720,...,0.0,960,50154.623118,46986.439003,-33017.251894,50154.623118,57326.150416,-3402.478513,2,1.0
27840,2015-10-07 12:11:00+00:00,mms1,0.179243,1.020115,0.319753,3.679535,3.753551,36.984257,50126.161307,57359.429224,...,0.0,960,50116.647184,47030.274796,-33032.563428,50116.647184,57370.491374,-3409.358087,2,1.0
27841,2015-10-07 12:12:00+00:00,mms1,0.202084,0.980422,0.314199,3.573832,3.503863,36.719220,50088.051144,57403.616182,...,0.0,960,50078.510185,47074.067018,-33047.610475,50078.510185,57414.647511,-3416.226608,2,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40829,2015-10-25 15:18:00+00:00,mms1,0.130725,1.233462,0.960934,4.981472,6.144456,1245.827900,47640.078650,50172.856962,...,0.0,960,47618.928887,43929.992238,-24830.291867,47618.928887,50173.683631,-5384.158116,2,0.0
40830,2015-10-25 15:19:00+00:00,mms1,0.118131,1.241140,0.944783,4.971576,6.170420,1277.581300,47555.377437,50176.056854,...,0.0,960,47534.159505,43949.864968,-24801.582954,47534.159505,50176.812289,-5384.861364,2,0.0
44715,2015-10-31 04:36:00+00:00,mms1,0.126159,1.070201,1.000000,5.532962,5.921381,846.869200,62782.555233,13938.356516,...,0.0,960,62797.175784,12454.452843,-6694.923151,62797.175784,13959.131416,-2253.451676,2,0.0
44716,2015-10-31 04:37:00+00:00,mms1,0.127368,1.175478,1.000000,5.113122,6.010361,1780.111600,62840.869608,14021.417996,...,0.0,960,62855.378337,12524.399732,-6741.192853,62855.378337,14042.167423,-2263.140882,2,0.0
44718,2015-10-31 04:39:00+00:00,mms1,0.116464,1.013668,1.000000,5.746482,5.825025,554.853150,62956.437692,14187.298137,...,0.0,960,62970.779377,12663.891991,-6833.965769,62970.779377,14208.009144,-2282.482789,2,0.0

In [8]:
in_df.loc[in_df['Epoch'] == tar_df.loc[27837, 'Epoch'], :].index[0]

52568